### PR TITLE
Log in

### PR DESCRIPTION
**Pull request by fkienhoefer**
UI of new post is done (at least as far as I am able to tell).
The LogIn screen still needs some minor work done on it (mainly a fix for the icons 
in the textInput views not being underlined) but is also mostly done.

Requested the pull so someone can look over the code.

Cheers

### CODE REVIEW

**Review by florianschmidt1994 — CHANGES_REQUESTED** [review]
Hey, I got it running and it looks pretty solid already. There are some things that I noticed that we could look over again:

- The spacing looks a little bit off for the input elements on the login screen, I don't know if this is an android / ios issue? 
image

- Are you planning on using the bg_login and bg_welcome assets on that screen? Otherwise we could leave them out of this PR to not have unnecessary files in there

- We need to use internationalization for our text strings in order to have them work in multiple languages. This is a hard requirement and needs to be adressed b.c. we have participants from multiple countries that are going to use the app

**Comment by fkienhoefer** [comment]
Just checked the spacing again, it looks fine under android on a Nexus 5x (apart from the still broken underline), it may very well be an android/iOS issue. On what device did you test it?

bg_login is currently in use as a placeholder in the "NewPost" screen. bg_welcome is not used and as such will be removed in the next commit.

I will look into a solution for internationalization and will hopefully be able to implement it tomorrow.

Cheers

**Comment by fkienhoefer** [comment]
Progress has been slow on my side for the past 3 weeks, sorry for that. If you want to test what's currently there you can switch the component used in Home.js between <LoginForm/> <NewPost/> and <ChallengeList/>

**Comment by florianschmidt1994** [comment]
We merged this functionality with a different PR now

**Pull request closed without merging**
